id = "asus-um5606-fan-state"
name = "ASUS UM5606 Fan State"
version = "1.1.7"
min_noctalia = "5.0.0"
author = "ThatOneCalculator"
license = "MIT"
tags = ["Bar", "System"]
icon = "car-fan"
description = "Set the fan state on the ZenBook S 16 UM5606"

[[service]]
id = "service"
entry = "service.luau"

[[widget]]
id = "widget"
entry = "widget.luau"
