id = "kermut572/ru-menu"
name = "RU Menu"
version = "2.0.0"
min_noctalia = "5.0.0"
author = "Kermut572"
license = "MIT"
tags = ["Bar", "Panel", "Launcher"]
icon = "menu"
description = "A customizable right-click menu for the bar."

[[service]]
id = "service"
entry = "service.luau"

[[widget]]
id = "widget"
entry = "widget.luau"
