id = "werwolv/kde-connect"
name = "KDE Connect"
version = "2.0.0"
min_noctalia = "5.0.0"
author = "WerWolv"
license = "GPLv2"
tags = ["Bar", "Desktop", "Utility", "System"]
icon = "device-mobile"
description = "A plugin integrating your mobile devices using KDE Connect."

[[setting]]
key = "hideIfDisconnected"
type = "bool"
label = "Hide if disconnected"
default = false
description = "Hide the bar button entirely if no device is connected"

[[widget]]
id = "widget"
entry = "widget.luau"

[[desktop_widget]]
id = "desktop"
entry = "desktop_widget.luau"

[[service]]
id = "service"
entry = "service.luau"
