id = "activate-linux"
name = "Activate Linux Watermark"
version = "1.1.0"
min_noctalia = "5.0.0"
author = "Preston Corless (pgattic)"
license = "MIT"
tags = ["Desktop", "Fun"]
icon = "brand-windows"
description = "Adds a watermark to the bottom-right of the screen similar to the one found on unactivated Windows 10/11"

[[setting]]
key = "customizeText"
type = "bool"
label = "Customize Text"
default = false
description = "Write some custom text to display"

[[setting]]
key = "firstLine"
type = "string"
label = "First Line"
default = "Activate Linux"
description = "First line of the watermark"

[[setting]]
key = "secondLine"
type = "string"
label = "Second Line"
default = "Go to Settings to activate Linux."
description = "Second line of the watermark"

[[desktop_widget]]
id = "watermark"
entry = "widget.luau"
